TEST/Areas/PoR_System/Models/UserDataViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TEST.Models;

namespace TEST.Areas.PoR_System.Models {
    public class UserDataSearchViewModel {
        public UserDataSearchConViewModel Condition { get; set; }
        public List<UserDataSearchTableViewModel> DataTable { get; set; }
        public int DataCount { get; set; }
        public string Channels { get; set; }
        public string Units { get; set; }
    }
    public class UserDataSearchConViewModel {
        [Display(Name = "單位")]
        public string ChannelId { get; set; }

        [Display(Name = "子單位")]
        public string UnitId { get; set; }

        [Display(Name = "使用者代號")]
        public string UserId { get; set; }

        [Display(Name = "使用者姓名")]
        public string UserName { get; set; }

        [Display(Name = "是否有效")]
        public bool InEff { get; set; }
    }
    public class UserDataSearchTableViewModel {
        [Display(Name = "單位")]
        public string FullName { get; set; }

        public SysUserDatas UserData { get; set; }
    }

    public class UserDataInsertViewModel {
        public SysUserDatas UserData { get; set; }
        public List<InsChannels> Channels { get; set; }
        public List<SysUnits> Units { get; set; }
        public List<SysCodes> SysRoles { get; set; }
        public List<SysCodes> SysRolesOpt1 { get; set; }
        public List<SysCodes> SysRolesOpt2 { get; set; }
        public InsAuthLevelDtls InsAuthLevelDtls { get; set; }
        public string UserRoleIds { get; set; }
        public string Operation { get; set; }
    }

    public class UserDataInsertParamModel : UserDataDeleteParamModel {
        public string UnitId { get; set; }
        public string UserName { get; set; }
        public string InsAgentId { get; set; }
        public string AgentFlag { get; set; }
        public string UserMail { get; set; }
        public string PersonalMail { get; set; }
        public string AgentId { get; set; }
        public string AgentRegNo { get; set; }
        public string AgentTel { get; set; }
        public string AgentMobile { get; set; }
        public string AgentAddress { get; set; }
        public string BusinessSrc { get; set; }
        public string CommSetupNo { get; set; }
        public string CommTypeFlag { get; set; }
        public string SupervisorFlag { get; set; }
        public string SupervisorUnitId { get; set; }
        public DateTime EffDate { get; set; }
        public DateTime ExpDate { get; set; }
        public string AuthLevel { get; set; }
        public string UserSuspendFlag { get; set; }
        public string AgentSuspendFlag { get; set; }
        public string MobileFlag { get; set; }
        public List<string> UserRoleIds { get; set; }
        public string SuspendReason { get; set; }
        public string AutoDirectBusiness { get; set; }
    }

    public class UserDataDeleteViewModel {

    }

    public class UserDataDeleteParamModel {
        public string ChannelId { get; set; }
        public string UserId { get; set; }
    }
}

TEST/Areas/PoR_System/Controllers/UserDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TEST.Models;
using TEST.Areas.PoR_System.Models;
using Newtonsoft.Json;


namespace TEST.Areas.PoR_System.Controllers {
    public class UserDataController : Controller {
        private tlgDbEntities db = new tlgDbEntities();

        // GET: PoR_System/UserData
        public ActionResult Index() {
            var model = new UserDataSearchViewModel();
            var channels = db.InsChannels.ToList();
            var units = db.SysUnits.ToList();

            var channelsData = new List<Dictionary<string, string>>();
            var unitsData = new List<Dictionary<string, string>>();

            foreach (var item in channels) {
                var map = new Dictionary<string, string>();
                map.Add("code", item.ChannelId);
                map.Add("value", item.ChannelName);
                channelsData.Add(map);
            }
            foreach (var item in units) {
                var map = new Dictionary<string, string>();
                map.Add("code", item.UnitId);
                map.Add("parentCode", item.ChannelId);
                map.Add("value", item.UnitName);
                unitsData.Add(map);
            }

            model.Channels = JsonConvert.SerializeObject(channelsData);
            model.Units = JsonConvert.SerializeObject(unitsData);

            return View(model);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Index(UserDataSearchViewModel model) {
            var query = from user in db.SysUserDatas
                        join unit in db.SysUnits on user.UnitId equals unit.UnitId
                        join channel in db.InsChannels on user.ChannelId equals channel.ChannelId
                        where (model.Condition.ChannelId == null || user.ChannelId == model.Condition.ChannelId)
                        && (model.Condition.UnitId == null || user.UnitId == model.Condition.UnitId)
                        && (model.Condition.UserId == null || user.UserId == model.Condition.UserId)
                        && (model.Condition.UserName == null || user.UserName == model.Condition.UserName)
                        select new UserDataSearchTableViewModel { FullName = channel.ChannelName + "-" + unit.UnitName, UserData = user };

            model.DataTable = query.ToList();
            model.DataCount = query.Count();

            return View(model);
        }

        public ActionResult Edit(string channelId, string unitId, string userId) {
            var model = new UserDataInsertViewModel();

            var sysRoles = new List<SysCodes>();
            var sysRolesOpt1 = new List<SysCodes>();
            var sysRolesOpt2 = new List<SysCodes>();

            sysRolesOpt1 = db.SysCodes.Where(m => m.CodeType == "SysRole").ToList();
            sysRolesOpt2 = db.SysCodes.Where(m => m.CodeType == "ChannelSysRole").ToList();

            sysRoles = sysRolesOpt1;
            //if ("1".equals(b2bUser.getChannelType()))
            //    sysRoles = sysRolesOpt1;
            //else
            //    sysRoles = sysRolesOpt2;

            SysUserDatas user = null;
            var emptyUser = new SysUserDatas();
            var userroleids = new List<string>();
            var insAuthLevelDtls = new InsAuthLevelDtls();

            if (userId != null) {
                user = db.SysUserDatas.Find(channelId, userId);
                userroleids = db.SysUserRoles.Where(x => x.ChannelId == channelId && x.UserId == userId).Select(x => x.UserRoleId).ToList();
                var dtls = db.InsAuthLevelDtls.Where(x => x.UserId == userId && x.InsClass == "F").ToList();
                if (dtls.Count > 0)
                    insAuthLevelDtls = dtls[0];
            }
            else {
                if (channelId != null && unitId != null) {
                    emptyUser.ChannelId = channelId;
                    emptyUser.UnitId = unitId;
                }
            }

            model.Channels = db.InsChannels.ToList();
            model.Units = db.SysUnits.ToList();
            model.SysRoles = sysRoles;
            model.SysRolesOpt1 = sysRolesOpt1;
            model.SysRolesOpt2 = sysRolesOpt2;
            model.UserData = user ?? emptyUser;
            model.InsAuthLevelDtls = insAuthLevelDtls;
            model.UserRoleIds = JsonConvert.SerializeObject(userroleids);
            model.Operation = string.IsNullOrEmpty(userId) ? "insert" : "update";

            return View(model);
        }

        [HttpPost]
        public ActionResult Insert(UserDataInsertParamModel model) {
            var record = new SysUserDatas();
            record.ChannelId = model.ChannelId;
            record.UnitId = model.UnitId;
            record.UserName = model.UserName;
            record.UserId = model.UserId;
            record.AgentFlag = model.AgentFlag;
            record.UserMail = model.UserMail;
            record.PersonalMail = model.PersonalMail;
            record.AgentId = model.AgentId;
            record.AgentRegNo = model.AgentRegNo;
            record.AgentTel = model.AgentTel;
            record.AgentMobile = model.AgentMobile;
            record.AgentAddress = model.AgentAddress;
            record.BusinessSrc = model.BusinessSrc;
            record.CommSetupNo = model.CommSetupNo;
            record.CommTypeFlag = model.CommTypeFlag;
            record.SupervisorFlag = model.SupervisorFlag;
            record.SupervisorUnitId = model.SupervisorUnitId;
            record.UserSuspendFlag = model.UserSuspendFlag;
            record.InsAgentId = model.InsAgentId;
            record.MobileFlag = model.MobileFlag;
            if (model.UserSuspendFlag == "Y") record.UserSuspendDate = new DateTime();
            record.AgentSuspendFlag = model.AgentSuspendFlag;
            if (model.AgentSuspendFlag == "Y") record.AgentSuspendDate = new DateTime();
            record.EffDate = model.EffDate;
            record.ExpDate = model.ExpDate;
            record.SuspendReason = model.SuspendReason;
            record.AutoDirectBusiness = model.AutoDirectBusiness;

            int result = 0;
            var customers = db.Set<SysUserDatas>();
            customers.Add(record);

            try {
                //result = userdatasMapper.insertSelective(record);
                result = db.SaveChanges();
            }
            catch (Exception) {
                //throw new B2bDuplicateKeyException("使用者資料", "使用者代號", model.UserId(), "userId");
                throw;
            }

            DeleteUserRoles(record);
            if (model.UserRoleIds != null) {
                InsertUserRoles(record, model.UserRoleIds);
            }
            DeleteInsAuthLevelDtls(model.UserId);
            if (model.AuthLevel != null) {
                InsertInsAuthLevelDtls(model);
            }

            return Json(result);
        }
        [HttpPut]
        public ActionResult Update(UserDataInsertParamModel model) {
            var data = db.SysUserDatas.Find(model.ChannelId, model.UserId);
            data.UserName = model.UserName;
            data.UserId = model.UserId;
            data.AgentFlag = model.AgentFlag;
            data.UserMail = model.UserMail;
            data.PersonalMail = model.PersonalMail;
            data.AgentId = model.AgentId;
            data.AgentRegNo = model.AgentRegNo;
            data.AgentTel = model.AgentTel;
            data.AgentMobile = model.AgentMobile;
            data.AgentAddress = model.AgentAddress;
            data.BusinessSrc = model.BusinessSrc;
            data.CommSetupNo = model.CommSetupNo;
            data.CommTypeFlag = model.CommTypeFlag;
            data.SupervisorFlag = model.SupervisorFlag;
            data.SupervisorUnitId = model.SupervisorUnitId;
            data.EffDate = model.EffDate;
            data.ExpDate = model.ExpDate;
            data.UserSuspendFlag = model.UserSuspendFlag;
            data.AgentSuspendFlag = model.AgentSuspendFlag;
            data.InsAgentId = model.InsAgentId;
            data.MobileFlag = model.MobileFlag;

            // 找出原本user資料 與輸入的參數停權註記做判斷
            if (data.UserSuspendFlag == "Y" && model.UserSuspendFlag == "N")
                data.UserReinstateDate = new DateTime();

            // 批次匯入沒設定為null 視為預設值N
            if ((data.UserSuspendFlag == "N" || string.IsNullOrEmpty(data.UserSuspendFlag)) && model.UserSuspendFlag == "Y")
                data.UserSuspendDate = new DateTime();
            if (data.AgentSuspendFlag == "Y" && model.AgentSuspendFlag == "N")
                data.AgentReinstateDate = new DateTime();
            if ((data.AgentSuspendFlag == "N" || string.IsNullOrEmpty(data.AgentSuspendFlag)) && model.AgentSuspendFlag == "Y")
                data.AgentSuspendDate = new DateTime();

            data.SuspendReason = model.SuspendReason;
            data.AutoDirectBusiness = model.AutoDirectBusiness;

            int result = db.SaveChanges();
            if (result == 0) {
                //throw new B2bNoMatchException("使用者資料", "使用者代號", model.UserId(), "userId");
                //throw;
            }
            DeleteUserRoles(data);
            if (model.UserRoleIds != null) {
                InsertUserRoles(data, model.UserRoleIds);
            }
            DeleteInsAuthLevelDtls(model.UserId);
            if (model.AuthLevel != null) {
                InsertInsAuthLevelDtls(model);
            }

            return Json(result);
        }
        [HttpDelete]
        public ActionResult Delete(UserDataDeleteParamModel model) {
            var key = db.SysUserDatas.Find(model.ChannelId, model.UserId);
            db.SysUserDatas.Remove(key);
            int result = db.SaveChanges();
            if (result == 0) {
                //throw new B2bNoMatchException("使用者資料", "使用者代號", param.getUserId(), "userId");
            }
            DeleteUserRoles(key);
            DeleteInsAuthLevelDtls(model.UserId);

TEST/Areas/PoR_System/Views/UserData/Index.cshtml
@using TEST.Areas.PoR_System.Models
@model UserDataSearchViewModel

@section head {
    <link rel="stylesheet" href="~/Content/autocomplete.css">
}

<div class="container-fuild">
    <!--Start breadcrumb-->
    <nav aria-label="breadcrumb-item" class="breadcrumb-wrap">
        <div class="main-cont cont-wid">
            <ol class="breadcrumb m-0 px-0">
                @*<li class="breadcrumb-item"><a href="${appUrl.sys}/index">首頁</a></li>
                    <li class="breadcrumb-item">
                        <a href="${appUrl.sys}/insClass/sys">系統維運</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="${basePath}/userData/search">使用者管理</a>
                    </li>*@
            </ol>
        </div>
    </nav>
    <!--End breadcrumb-->
    <!--Strat main-cont-->
    <div class="main-cont cont-wid">
        <!--class:cont-wid PC:1280px, pad:1024px, mobile:480px-->
        @using (Html.BeginForm("Index", "UserData", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
            <h1 class="main-title mt-4">使用者管理</h1>
            <!-- 頁面第一個大標請加上.mt-4 -->
            <!--Start search-bar-->
            <div class="section search-bar">
                <div class="row no-gutters">
                    <div class="col-md-6 mb-2">
                        <div class="input-group">
                            @Html.LabelFor(m => m.Condition.ChannelId, new { @class = "form-label col-md-4" })
                            <div class="col-md">
                                @*<input type="text" class="form-control" id="channelId" data-channels='@Model.channels' placeholder="請輸入通路" autocomplete="off">*@
                                @Html.TextBoxFor(m => m.Condition.ChannelId, new { @class = "form-control", @id = "channelId", data_channels = Model.Channels })
                            </div>
                            <div class="col-md">
                                <input type="text" class="form-control" id="unitId" placeholder="" data-units="@Model.Units" autocomplete="off">
                                @*@Html.TextBoxFor(m => m.Condition.UnitId, new { @class = "form-control" })*@
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input-group mb-2">
                            @Html.LabelFor(m => m.Condition.InEff, new { @class = "form-label col-md-4" })
                            <div id="inEff" class="col-md-7">
                                <label class="radio-inline">
                                    @Html.RadioButtonFor(m => m.Condition.InEff, true)是
                                </label> <label class="radio-inline">
                                    @Html.RadioButtonFor(m => m.Condition.InEff, false)否
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input-group mb-2">
                            @Html.LabelFor(m => m.Condition.UserId, new { @class = "form-label col-md-4" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.Condition.UserId, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                    <div class="col-md-6">
                        <div class="input-group mb-2">
                            @Html.LabelFor(m => m.Condition.UserName, new { @class = "form-label col-md-4" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.Condition.UserName, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                    <div class="col-md-12 btn-wrap btn-col-2 text-center">
                        <input type="submit" value="查詢" class="btn btn-default" />
                        @*<button class="btn btn-primary" onclick="edit()">
                                <i class="fa fa-plus" aria-hidden="true"></i> 新增
                            </button>*@
                        <input type="button" value="新增" onclick="edit()" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
        <!--End search-bar-->
        <!--Start search-result-->
        @if (Model != null && Model.DataTable != null) {
            <h1 class="main-title">
                搜尋結果
                <p class="section-text float-right mb-0">
                    本次查詢總筆數 <span class="text-highlight">@Model.DataCount</span> 筆
                </p>
            </h1>
            <table class="table table-ui table-striped table-responsive-md text-center">
                <tr>
                    <th>單位</th>
                    <th>使用者代號</th>
                    <th>使用者姓名</th>
                    <th>生效日期</th>
                    <th>失效日期</th>
                    <th>功能</th>
                </tr>

                @foreach (var item in Model.DataTable) {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.UserData.UserId)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.UserData.UserName)
                        </td>
                        <td>
                            @if (item.UserData.EffDate == null) {
                                @:不設限
                            }
                            else {
                                @Html.ValueFor(m => item.UserData.EffDate, "{0:yyyy-MM-dd}")
                            }
                        </td>
                        <td>
                            @if (item.UserData.ExpDate == null) {
                                @:不設限
                            }
                            else {
                                @Html.ValueFor(m => item.UserData.ExpDate, "{0:yyyy-MM-dd}")
                            }
                        </td>
                        <td>
                            <button class="btn btn-default form-btn" onclick="edit('@item.UserData.ChannelId','@item.UserData.UnitId','@item.UserData.UserId')">
                                <i class="fa fa-pencil-square-o" aria-hidden="true">修改</i>
                            </button>
                            <button class="btn btn-danger form-btn" onclick="deleteUser(this,'@item.UserData.ChannelId','@item.UserData.UserId')">
                                <i class="fa fa-pencil-square-o" aria-hidden="true">刪除</i>
                            </button>
                        </td>
                    </tr>
                }
            </table>
        }
        <!--End search-result-->

    </div>
    <!--End main-cont-->
</div>
<!--End container-fuild-->

@section scripts {
    <script type="text/javascript" src="~/Scripts/util/displaytagUtil.js"></script>
    <script type="text/javascript" src="~/Scripts/util/comboBoxUtil.js"></script>
    <script type="text/javascript" src="~/Scripts/util/autocomplete.js"></script>
    <script type="text/javascript">
        //	comboBoxAddSecondaryMenu("channelId", "unitId");
        $(document).ready(function () {
            //通路autocomplete
            var channels = $('#channelId').data('channels');
            autocomplete($('#channelId')[0], channels, true);
            $('#channelId').data('channels', '');
            $('#channelId').removeAttr('data-channels');

            var units = $('#unitId').data('units');
            autocomplete($('#unitId')[0], units, true, 'channelId');
            $('#unitId').data('units', '');
            $('#unitId').removeAttr('data-units');
        });

        function getUsers(url) {
            displaytagAjaxCall({
                type: 'GET',
                url: '${basePath}/userData/userTable',
                data: {
                    channelId: $('#channelId').attr('code') == undefined ? '' : $('#channelId').attr('code'),
                    unitId: $('#unitId').attr('code') == undefined ? '' : $('#unitId').attr('code'),
                    inEff: $('#inEff input:checked').val(),
                    userId: $('#userId').val(),
                    userName: $('#userName').val()
                },
                dataType: 'html',
                success: function (tbody) {
                    $("#userTable").empty();
                    $("#userTable").append(tbody);
                },
                error: function (error) {
                    alert(error.msg);
                }
            }, url, getUsers, "userTable");
        }

        function edit(channelId, unitId, userId) {
            window.location.href = "UserData/Edit"
                + (channelId && userId ? ("?channelId=" + channelId + "&unitId=" + unitId + "&userId=" + userId)
                    : "");
        }

        function deleteUser(element, channelId, userId) {
            if (!confirm("確實要刪除嗎?"))
                return;

            b2bAjaxCall({
                type: 'DELETE',
                url: '@Url.Action("Delete")',
                data: {
                    channelId: channelId,
                    userId: userId
                },
                success: function (data) {
                    alert('刪除成功');
                    $(element).parent().parent().remove();
                },
                error: function (error) {
                    alert(error.msg);
                }
            });
        }
    </script>
}